[project]
name = "sonarqube-mcp-server"
version = "0.0.1-beta"
description = "SonarQube MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.2",
    "httpx>=0.28.1",
]